## Set up following instructions from: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

theme: jekyll-theme-minimal
title: Emily R. Bamber
description: Geomorphologist
logo: /assets/images/profile.JPG


# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.linkedin.com/in/emily-bamber-447a65171/"
    - "https://github.com/eb-mars"
    - "mailto:eb2043@cam.ac.uk"
    - "https://orcid.org/0000-0002-3920-4970"
    - "https://scholar.google.com/citations?user=PSM83ZsAAAAJ&hl=en"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:eb2043@cam.ac.uk
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=PSM83ZsAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eb-mars"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/emily-bamber-447a65171/"
    - label: "Curriculum Vitae (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/bamber_cv.pdf"

# For the About Page?
events:
- image: "/assets/images/timeline/RGB_CAM.png"
  date: "Oct 2024 - Present"
  description: "Research Fellow in Earth Sciences, Trinity College, University of Cambridge"
- image: "/assets/images/timeline/RGB_UTA.png"
  date: "Aug 2024"
  description: "PhD, Geoscience, The University of Texas at Austin"
- image: "/assets/images/timeline/RGB_Oxford.png"
  date: "June 2018"
  description: "Master of Earth Science, Earth Sciences, The University of Oxford"


timeline-img: ""
